global:
  smtp_smarthost: '<SMTP_HOST>'
  smtp_from: 'alertmanager@example.com'
  smtp_require_tls: False

# The root route with all parameters.
route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'example'

receivers:
- name: 'example'
  email_configs:
  - to: '<YOUR_EMAIL>'