version: "3"
services:
  flask:
    build: ./flask
    entrypoint:
      - gunicorn
      - -c=conf.py
      - -w=2
      - -b=0.0.0.0:5000
      - app:app
    environment:
      FLASK_DEBUG: 1
      prometheus_multiproc_dir: /tmp #required for multiprocess mode of prometheus_client. This should point to a directory to store the metrics.
    ports: ["5000:5000"]
    volumes: ["./flask/:/usr/src/app/"]
  prometheus:
    image: "quay.io/prometheus/prometheus"
    ports: ["9090:9090"]
    volumes: ["./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml",
              "./prometheus/alerts.yml:/etc/prometheus/alerts.yml"]
  alertmanager:
    image: "quay.io/prometheus/alertmanager"
    ports: ["9093:9093"]
    volumes:
      - ./alertmanager/:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'